### PR TITLE
Feature/installation tweaks

### PR DESCRIPTION
**Pull request by LindaJeanne**
Let's pull this through into Develop, and I'll start a new branch locally for the tabs work.

### CODE REVIEW

**Comment by LindaJeanne** [comment]
Hmm... looking into the conflicts. Hold on...

**Comment by LindaJeanne** [comment]
Alright, removing the conflicts, I accidentally created more by pulling Eli's feature changes in, which is confusing the algorithm. Gah. Hold on...

**Comment by elizoller** [comment]
I thought they were already in with bb6c367

**Comment by LindaJeanne** [comment]
Yeah, not sure what happend. Let me try to back out of whatever I did. Hold on...

**Pull request closed without merging**
